server:
  port: 3000

spring:
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/school-system
      auto-index-creation: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

logging:
  file: app.log
  level:
    root: INFO
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

jwt:
  secret: EDkSgdGptvg70eQXVrt3MPt46e3qG0
  expireAt: 30
upload:
  location: /src/main/resources/static/userPhotos


app:
  config:
    backend:
      resource:
        user: /user/img/{filename:.+}
      auth:
        base-uri: /api/v1/auth
        api:
          login-uri: /login
          signup-uri: /signup
      user:
        base-uri: /api/v1/users
        api:
          load-all-users-uri: /all
          load-user-by-id-uri: /{userId}
          load-me-uri: /getMe
          load-search-users-uri: /search
          create-user-uri: /createUser
          update-me-uri: /updateMe
          update-my-photo-uri: /updateMyPhoto
      school:
        base-uri: /api/v1/schools
        api:
          load-all-schools-uri: /all
          load-school-by-id-uri: /{schoolId}
          load-search-schools-uri: /search
          create-school-uri: /createSchool
          load-all-classrooms-by-school-uri: /{schoolId}/classrooms
          create-school-classroom-uri: /{schoolId}/classrooms/{classroomId}
          remove-school-classroom-uri: /{schoolId}/classrooms/{classroomId}
      classroom:
        base-uri: /api/v1/schools/{schoolId}/classrooms
        api:
          load-all-classrooms-uri: /all
          load-classroom-by-id-uri: /{classroomId}
          load-search-classrooms-uri: /search
          create-classroom-uri: /createClassroom
          update-classroom-uri: /{classroomId}
          remove-classroom-uri: /{classroomId}
          load-all-students-by-classroom-uri: /{classroomId}/students
      enrollment:
        base-uri: /api/v1/users/{userId}
        api:
          load-all-enrollments-by-user-uri: /enrollments
          create-user-enrollment-uri: /enrollments/{classroomId}
          remove-user-enrollment-uri: /enrollments/{classroomId}


file:
  upload:
    base-dir: uploads
    user:
      dir: userPhotos